"""
Blast Radius Agent — PR Generator
===================================
Generates pull request descriptions and diffs from approved changes.
"""

import json
import tempfile
import difflib
from datetime import datetime
from pathlib import Path
from typing import Optional


class PRGenerator:
    """Generate professional PR text files from analysis and changes."""

    def __init__(self, ticket_id: str = "UNKNOWN", project_root: str = "."):
        """Initialize PR generator."""
        self.ticket_id = ticket_id
        self.project_root = Path(project_root).resolve()
        self.risk_level = "UNKNOWN"
        self.analysis = {}
        self.approved_changes = []

    def set_analysis(self, analysis: dict):
        """Set the blast radius analysis data."""
        self.analysis = analysis
        # Extract risk level
        if "4. RISK LEVEL" in analysis:
            risk_text = analysis["4. RISK LEVEL"].upper()
            for level in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
                if level in risk_text:
                    self.risk_level = level
                    break

    def set_changes(self, changes: list[dict]):
        """Set the approved changes."""
        self.approved_changes = changes

    def generate_unified_diff(self, before: str, after: str, filename: str = "changes") -> str:
        """
        Generate unified diff between before and after content.

        Returns:
            Unified diff string suitable for git apply.
        """
        before_lines = before.splitlines(keepends=True)
        after_lines = after.splitlines(keepends=True)

        diff = difflib.unified_diff(
            before_lines,
            after_lines,
            fromfile=f"a/{filename}",
            tofile=f"b/{filename}",
            lineterm="",
        )

        return "\n".join(diff)

    def generate_pr_description(self) -> str:
        """
        Generate a comprehensive PR description.

        Returns:
            Formatted PR description.
        """
        lines = []

        # Header
        lines.append(f"# PR: {self.ticket_id} - Blast Radius Fix")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append(
            f"This PR addresses the blast radius impact of changes in **{self.ticket_id}**."
        )
        lines.append("")

        # Risk Assessment
        lines.append("## Risk Assessment")
        lines.append(f"**Risk Level:** `{self.risk_level}`")
        lines.append("")

        if self.analysis:
            if "1. WHAT WAS DONE" in self.analysis:
                lines.append("### What Was Done")
                lines.append(self.analysis["1. WHAT WAS DONE"])
                lines.append("")

            if "2. ROOT CAUSE / RISK ORIGIN" in self.analysis:
                lines.append("### Root Cause")
                lines.append(self.analysis["2. ROOT CAUSE / RISK ORIGIN"])
                lines.append("")

            if "3. IMPACTED MODULES" in self.analysis:
                lines.append("### Impacted Modules")
                lines.append(self.analysis["3. IMPACTED MODULES"])
                lines.append("")

        # Changes
        lines.append("## Changes Included")
        if self.approved_changes:
            for i, change in enumerate(self.approved_changes, 1):
                filepath = change.get("file", "unknown")
                operation = change.get("operation", "unknown").upper()
                lines.append(f"{i}. **{operation}** — `{filepath}`")
        else:
            lines.append("- No changes specified")
        lines.append("")

        # Testing
        lines.append("## Testing Recommendations")
        if self.analysis and "5. SUGGESTED FIX / MITIGATION" in self.analysis:
            lines.append(self.analysis["5. SUGGESTED FIX / MITIGATION"])
        else:
            lines.append(
                "1. Run full test suite to verify no regressions\n"
                "2. Check all impacted modules compile/type-check\n"
                "3. Validate dependent services still work"
            )
        lines.append("")

        # Merge notes
        lines.append("## Merge Notes")
        lines.append(f"- **Generated by:** Blast Radius Agent (AI-powered impact analysis)")
        lines.append(f"- **Date:** {datetime.now().isoformat()}")
        lines.append(f"- **Ticket ID:** {self.ticket_id}")
        lines.append("")

        return "\n".join(lines)

    def generate_full_pr_text(self) -> str:
        """
        Generate complete PR text file with description and all diffs.

        Returns:
            Full PR text with embedded diffs.
        """
        lines = []

        # PR Description
        lines.append(self.generate_pr_description())

        # Diffs
        if self.approved_changes:
            lines.append("---")
            lines.append("")
            lines.append("## Detailed Changes (Unified Diff Format)")
            lines.append("")

            for change in self.approved_changes:
                filepath = change.get("file", "unknown")
                operation = change.get("operation", "unknown")
                lines.append(f"### File: {filepath} ({operation})")
                lines.append("")

                if operation == "modify" and "diff" in change:
                    lines.append("```diff")
                    lines.append(change["diff"])
                    lines.append("```")
                elif operation == "create" and "content" in change:
                    lines.append("```")
                    lines.append(change["content"][:500])  # First 500 chars
                    if len(change["content"]) > 500:
                        lines.append("... (truncated)")
                    lines.append("```")
                elif operation == "delete":
                    lines.append("*File will be deleted*")

                lines.append("")

        return "\n".join(lines)

    def save_pr_text(self, output_dir: str = "outputs", filename: str = "candidate_pr.txt") -> str:
        """
        Save PR text to file.

        Returns:
            Path to saved PR file.
        """
        output_path = Path(output_dir) / filename
        output_path.parent.mkdir(parents=True, exist_ok=True)

        pr_text = self.generate_full_pr_text()
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(pr_text)

        return str(output_path.resolve())

    def save_pr_json(self, output_dir: str = "outputs", filename: str = "candidate_pr.json") -> str:
        """
        Save PR as structured JSON.

        Returns:
            Path to saved JSON file.
        """
        output_path = Path(output_dir) / filename
        output_path.parent.mkdir(parents=True, exist_ok=True)

        pr_data = {
            "title": f"{self.ticket_id} - Blast Radius Fix",
            "description": self.generate_pr_description(),
            "risk_level": self.risk_level,
            "ticket_id": self.ticket_id,
            "changes": self.approved_changes,
            "generated_at": datetime.now().isoformat(),
        }

        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(pr_data, f, indent=2)

        return str(output_path.resolve())
